### ISSUE TITLE
Cursor jumping due to MatchParen settings

### ISSUE THREAD

**Issue by GerbenWelter** [talha-akram/noctis.nvim#2]
Thank you for making these beautiful colorschemes available for Neovim.

While navigating code I noticed the cursor jumped around when it was on a matching parenthesis or bracket. This made navigating very confusing. At first I thought it was due to some Neovim setting but then I found out it was only when using the noctis colorschemes. I found the setting responsible for this behavior [here](https://github.com/talha-akram/noctis.nvim/blob/main/lua/noctis_theme.lua#L52). Changing `reverse` to `false` made me regain my sanity ;-)

Was this setting done deliberately? If so, can it be made configurable?

**Comment by talha-akram** [comment]
Thank you so much for reporting this issue, I really appreciate the details provided!

I have updated it use an underline instead which still lets us identify bracket pairs but doesn't cause the jarring effect you have reported.

#### Normal mode
<img width="639" alt="image" src="https://user-images.githubusercontent.com/72861924/216647165-948d71a3-08a9-4fd6-a974-83e4eccba963.png">

#### Insert mode:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/72861924/216647022-264195d9-3be6-4751-86e0-573ee0642622.png">

**Comment by GerbenWelter** [comment]
Much better! Thank you very much.
