### ISSUE TITLE
Option to disable highlighting of certain elements?

### ISSUE THREAD

**Issue by manoelpqueiroz** [talha-akram/noctis.nvim#6]
Hi guys,

First of all, thank you for porting Noctis over to Neovim, I truly believe this is one of the best color schemes out there, and having it makes my transition from VS Code to Neovim so much easier.

One thing that I'm not sure if it's intentional with the design is the apparent highlight of certain elements which would seem better if more integrated with the rest of the UI. The most clear one for me is the sidebar (see below for a comparison of how it is highlighted in Noctis, but seems to blend well with [rose-pine](https://github.com/rose-pine/neovim)): 

### Noctis

![Spectacle_2024 11 10_12 46_01](https://github.com/user-attachments/assets/66e71f34-8886-4cdf-bfaf-403287b4f644)

### Rosé Pine

![Spectacle_2024 11 10_12 48_03](https://github.com/user-attachments/assets/57d1e9f6-2fba-477a-acd5-2d46eccba909)

----

Have you considered the factors that make this highlight appear with Noctis? Is it possible to override in plugin configuration or does it need change in the colorscheme's source code?

Thank you very much in advance!

**Comment by talha-akram** [comment]
Thank you for reporting this issue, it has been addressed in the latest commit to `main`.
> Is it possible to override in plugin configuration or does it need change in the colorscheme's source code?

You can override any of the defined highlight groups by linking them to another one or by redefining them to use different values using `:highlight`. You would have to do this after the point where you are calling `:colorscheme` to set a theme. Hope this helps!

**Comment by talha-akram** [comment]
And to clear a specific highlight rule you can use `:highlight clear $HIGHLIGH_GROUP_NAME` e.g.:
```vim
:highlight clear CursorColumn
```

**Comment by talha-akram** [comment]
Closing as the issue has been addressed in main.

**Comment by manoelpqueiroz** [comment]
Thank you for the comments, @talha-akram! I'm currently ramping up my familiarity with Neovim configs and your tips have proved very helpful for me to speed up the learning process. Keep up the good work!
